name: data_validation
channels:
  - defaults
dependencies:
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=7.0.1=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyterlab=3.1.7=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.8.2=pyhd3eb1b0_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - pip
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pip:
    - pandas==1.3.3
    - jupyter_server==1.4.1
    - markupsafe==2.0.1
    - jupyter_core==4.8.1
    - numpy==1.21.2
    - ipython==7.27.0
    - notebook==6.4.3
    - pandocfilters==1.4.3
    - numexpr==2.7.3
    - matplotlib==3.4.3
    - ipykernel==6.4.1